### ISSUE TITLE
Target Thumbnails are blank

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa#6]
I was under the impression that when you click on a collection there should be a thumbnail for each target. At the moment these are all blank. 

e.g. https://beta.webarchive.org.uk/ukwa/collection/329

![target thumbnails](https://cloud.githubusercontent.com/assets/16339290/21453019/20b6755e-c903-11e6-90ec-b6ab8808bfad.jpg)

**Comment by ldbiz** [comment]
Presumably, the issue is one or more of:

The service generating them either isn't working or isn't accessible.
The wrong service address is being used.
The target key needed by the service are incomplete or invalid within the collection data.

@anjackson please take a look and advise.

**Comment by ldbiz** [comment]
I notice that when I use what I assume is the service url (prod.conf>screenshotter.prefix) and an ID, I get errors though this may be me using an invalid key.

eg. 

http://webrender.bl.uk/webtools/image/3814 
returns
ExtractionError at /webtools/image/3814
Can't extract file(s) to egg cache
The following error occurred while trying to extract file(s) to the Python egg
cache:
[Errno 13] Permission denied: '/var/www/.python-eggs'

etc.

**Comment by ldbiz** [comment]
As an aside, the error page indicates debug mode on a publicly accessible website, giving quite a bit of information out, just flagging a possible security issue.

**Comment by chrispeacockbl** [comment]
The URL being used is:

<wayback.prefix>/1990/<target primary URL>

I'm guessing the "/1990/" could be a problem?

**Comment by ldbiz** [comment]
I'm assuming its the screenshotter, not wayback. Seperate issue, wayback has been fixed.

**Comment by chrispeacockbl** [comment]
Following the code, this is an example of what might get used:

http://webrender.bl.uk/webtools/image/www.webarchive.org.uk/wayback-beta/archive/1990/lostvoiceguy.com

But yes, the above error happens for this too.

**Comment by anjackson** [comment]
There's a couple of issues here - firstly, the Solr back-end either does not seem to support the flag which declares whether a site is open access or not (i.e. whether we have permission to make it openly accessible.)

Secondly, at present, we can *only* present thumbnails for those sites that are openly licensed. The current site is showing the naff behaviour I came up with to show a site that we have but that is inaccessible. Note that most are inaccessible, although this will improve when we import the WCT data.

Additionally, it seems the Solr back-end only includes the 'published' Collections. This flag is a bit misleading, as we actually want all Collections to be published, but only a few to be 'promoted', meaning 'explicitly listed in the collections browser'.

**Comment by chrispeacockbl** [comment]
@anjackson Most of these points are addressed in the most recent version of the data import to Solr. The data currently available is from the older version of the import, possibly because I forgot to mention the script in my description of what had changed since July when this was all recently deployed. 

The only thing not addressed is the inclusion of collections other than published ones. I'm a bit confused by the above - what's the distinction between being published and being listed in the Collections Browser as far as the Collections Browser is concerned? Is it to do with targets underneath the said collections?

**Comment by anjackson** [comment]
I'm going to close this as we are writing thumbnails out of scope for now.
