### ISSUE TITLE
Add a field to indicate which Targets are Open Access

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa#7]
If it's not already present, we need a field in the Solr back-end that indicates whether a Target is open access.

**Comment by chrispeacockbl** [comment]
Hi Andy, we already have this. The field is 'licenses' and the consumer of the index should check for any content, e.g.:
`target.isOpenAccess = solrDocument.getFieldValues("licenses") != null && solrDocument.getFieldValues("licenses").size() > 0;`

I think I mentioned this to someone in either an email or Slack reply a few weeks ago, so Mars Spiders are aware I think.

**Comment by anjackson** [comment]
Thanks Chris.
